config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :user, only: %i[create update show]
  post :session, to: 'users#create_session'
  delete :session, to: 'users#destroy_session'
  get '/confirm/:email_confirmation_token', to: 'users#confirm_email', as: 'confirm_email'
  post '/password/recovery', to: 'users#password_recovery', as: 'password_recovery'
  get '/password/recovery', to: 'users#password_recovery'
  get '/password/reset/:password_recovery_token', to: 'users#password_reset', as: 'password_reset'
  post '/password/reset/:password_recovery_token', to: 'users#password_update', as: 'password_update'
  get '/register', to: 'users#register', as: 'register'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_secure_token :auth_token
  has_secure_token :email_confirmation_token
  has_secure_token :password_recovery_token
  after_commit :send_confirmation_email, only: %i[create update], if: -> { saved_change_to_unconfirmed_email? && !unconfirmed_email.nil? }

  validates :email, length: 1..100, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_nil: true
  validates :unconfirmed_email, exclusion: { in: ->(u) { [u.email] } }, length: 1..100, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_nil: true
  validates :username, presence: true, uniqueness: true, length: 3..32
  validates :password, length: 10..72, allow_nil: true
  validates :auth_token, uniqueness: true, allow_nil: true
  validates :email_confirmation_token, uniqueness: true, allow_nil: true
  validates :password_recovery_token, uniqueness: true, allow_nil: true

  private

  def send_confirmation_email
    regenerate_email_confirmation_token
    UserMailer.email_confirmation(self, unconfirmed_email).deliver_later
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :check_token, except: %i[show update destroy_session]

  def show
    @user = current_user
  end

  def register
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      render :confirmation, formats: [:html], locals: { title: 'Success!', body: 'Your account has been created.' }, status: :created
    else
      render :register, formats: [:html], status: :bad_request
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      render status: :ok, action: :show
    else
      @user.errors.add(:email, @user.errors.delete(:unconfirmed_email)) if @user.errors.include?(:unconfirmed_email)
      render status: :bad_request, json: @user.errors
    end
  end

  def confirm_email
    @user = User.find_by(email_confirmation_token: params[:email_confirmation_token])
    if @user&.update(email: @user.unconfirmed_email, unconfirmed_email: nil, email_confirmation_token: nil)
      render :confirmation, formats: [:html], locals: { title: 'Success!', body: 'Your email has been confirmed.' }
    else
      render :error, formats: [:html], locals: { title: 'Email Confirmation' }, status: :bad_request
    end
  end

  def create_session
    @user = User.find_by(username: params[:username])
    if @user&.authenticate(params[:password])
      render status: :ok, json: { token: @user.auth_token }
    else
      render status: :bad_request, json: { error: 'Invalid username or password.' }
    end
  end

  def destroy_session
    current_user.regenerate_auth_token
    head :ok
  end

  def password_recovery
    @user = User.find_by(username: params[:username])
    if @user&.email.present?
      @user.regenerate_password_recovery_token
      UserMailer.password_recovery(@user).deliver_later
    end

    render :confirmation, formats: [:html], locals: { title: 'Email Sent', body: "If there is an account registered to  #{params[:username]} we have sent instructions for how to reset your password." } if params[:commit] == 'Recover Account'
  end

  def password_reset
    @user = User.find_by(password_recovery_token: params[:password_recovery_token])
    render :error, formats: [:html], locals: { title: 'Reset Password' }, status: :bad_request if @user.nil?
  end

  def password_update
    @user = User.find_by(password_recovery_token: params[:password_recovery_token])
    if @user&.update(password_params)
      render :confirmation, formats: [:html], locals: { title: 'Success!', body: 'Your password has been updated.' }
    elsif @user
      render :password_reset, formats: [:html]
    else
      render :error, formats: [:html], locals: { title: 'Reset Password' }, status: :bad_request
    end
  end

  private

  def user_params
    params.require(:user).tap { |p| p[:unconfirmed_email] = p[:email] }.permit(:unconfirmed_email, :username, :password)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation).tap { |p| p[:password_recovery_token] = nil }
  end
end

app/views/users/confirmation.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0"><%= title %></h3>
        </div>
        <div class="card-body">
          <p class="lead"><p></p><%= body %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/email_confirmation.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0">Success!</h3>
        </div>
        <div class="card-body">
          <p class="lead"><strong>Your email has been confirmed.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/error.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0"><%= title %></h3>
        </div>
        <div class="card-body">
          <p class="lead"><strong>This link isn't working anymore.</strong> You can request a new link to be sent to your email.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/password_recovery.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0">Password Recovery</h3>
        </div>
        <div class="card-body">
          <%= form_with model: @user, url: password_recovery_url, local: true do |form| %>
          <div class="form-group">
            <%= form.label :username, "Username" %>
            <%= form.text_field :username, class: "form-control", required: "" %>
            <p></p>
          </div>
          <div class="form-group">
            <%= form.submit "Recover Account", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/password_reset.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0">Reset Password</h3>
        </div>
        <div class="card-body">
          <%= form_with model: @user, url: password_update_url(password_recovery_token: params[:password_recovery_token]), local: true do |form| %>
          <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
            <% end %>
          </div>
          <% end %>
          <div class="form-group">
            <%= form.label :password, "New Password" %>
            <%= form.password_field :password, class: "form-control", required: "" %>
          </div>
          <div class="form-group">
            <%= form.label :password, "Confirm Password" %>
            <%= form.password_field :password_confirmation, class: "form-control", required: "" %>
            <p></p>
          </div>
          <div class="form-group">
            <%= form.submit "Change Password", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/password_reset_error.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0">Reset Password</h3>
        </div>
        <div class="card-body">
          <p class="lead"><strong>This link isn't working anymore.</strong> You can request a new link to be sent to your email.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/register.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-outline-secondary">
        <div class="card-header">
          <h3 class="mb-0">Account Registration</h3>
        </div>
        <div class="card-body">
          <%= form_with model: @user, url: user_url, local: true do |form| %>
          <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
            <% end %>
          </div>
          <% end %>
          <div class="form-group">
            <%= form.label :email, "Email" %>
            <%= form.text_field :email, class: "form-control", required: "" %>
            <p></p>
          </div>
          <div class="form-group">
            <%= form.label :username, "Username" %>
            <%= form.text_field :username, class: "form-control", required: "" %>
            <p></p>
          </div>
          <div class="form-group">
            <%= form.label :password, "Password" %>
            <%= form.password_field :password, class: "form-control", required: "" %>
            <p></p>
          </div>
          <div class="form-group">
            <%= form.submit "Register Account", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>